DATA_DIR = "./data/"
OUTPUT_DIR = './outputs/'
LOG_DIR = "./logs/"
SAVES_DIR = "./saves/"
CACHE_DIR = "./cache/"
WEIGHTS_NAME = "pytorch_model.bin"
CONFIG_NAME = "config.json"

MAX_SEQ_LENGTH = 80
TRAIN_BATCH_SIZE = 24
EVAL_BATCH_SIZE = 8
LEARNING_RATE = 2e-5
NUM_TRAIN_EPOCHS = 1
RANDOM_SEED = 42
GRADIENT_ACCUMULATION_STEPS = 1
WARMUP_PROPORTION = 0.1
OUTPUT_MODE = 'classification'